#!/usr/bin/env bash

set -Eeuo pipefail
umask 077

cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

fail() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

# Requirements
[[ $EUID -eq 0 ]] || fail 'Run with sudo: sudo bash install.sh'
[[ -t 0 ]] || fail 'An interactive terminal is required.'
[[ -f compose.yml && -f Dockerfile && -f frontend/Dockerfile ]] ||
  fail 'Run the installer from the project checkout.'

for command in docker curl openssl python3 getent mktemp cmp; do
  command -v "$command" >/dev/null 2>&1 || fail "Missing dependency: $command"
done

docker info >/dev/null 2>&1 || fail 'Docker daemon is not available.'
docker compose version >/dev/null 2>&1 || fail 'Docker Compose v2 is required.'

classify_host() {
  if [[ "$1" == localhost || "$1" == 127.0.0.1 ]]; then
    printf 'local\n'
    return 0
  fi

  python3 - "$1" <<'PY'
import ipaddress
import re
import sys

host = sys.argv[1]
try:
    ipaddress.IPv4Address(host)
except ipaddress.AddressValueError:
    label = r"[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?"
    if len(host) > 253 or not re.fullmatch(rf"(?:{label}\.)+{label}", host):
        sys.exit(1)
    if re.fullmatch(r"[0-9.]+", host):
        sys.exit(1)
    print("domain")
else:
    print("ip")
PY
}

printf '\n=== Uptime Platform installer ===\n\n'

# Keep the host and all existing secrets on retries.
if [[ -f .env ]]; then
  grep -Fxq '# Generated by Uptime Platform install.sh' .env ||
    fail 'Existing .env is not installer-managed; refusing to overwrite it.'

  host="$(sed -n 's/^UPTIME_HOST=//p' .env | head -n 1)"
  [[ -n "$host" ]] || fail 'Existing .env has no UPTIME_HOST.'

  printf 'Existing configuration found; keeping secrets and database.\n'
  printf 'For a retry, enter the original administrator email and organization.\n'
else
  while true; do
    read -r -p 'Address (localhost, domain or IPv4; blank: detect public IPv4): ' host ||
      fail 'Input canceled.'

    if [[ -z "$host" ]]; then
      if ! host="$(curl --noproxy '*' -4fsS --max-time 10 https://api.ipify.org)"; then
        printf 'Cannot detect public IPv4. Enter an address manually.\n' >&2
        continue
      fi
      printf 'Detected address: %s\n' "$host"
    fi

    host="${host,,}"
    if ! host_kind="$(classify_host "$host")"; then
      printf 'Invalid address. Enter localhost, a domain or IPv4 without a scheme or port.\n' >&2
      continue
    fi

    if [[ "$host_kind" == domain ]] && ! getent ahostsv4 "$host" >/dev/null; then
      printf 'Domain has no resolvable IPv4 address. Check DNS and try again.\n' >&2
      continue
    fi
    break
  done
fi

host_kind="$(classify_host "$host")" || fail 'Invalid address in .env.'

if [[ "$host_kind" == local ]]; then
  app_url="http://${host}:8080"
  printf '\nLocal mode: Caddy is not needed. URL: %s\n' "$app_url"
elif [[ "$host_kind" == domain ]]; then
  getent ahostsv4 "$host" >/dev/null || fail 'Domain does not resolve to IPv4.'
  app_url="https://${host}"
else
  app_url="https://${host}"
  printf '\nWARNING: IP mode uses Caddy private CA.\n'
  printf 'Remote browsers will not trust its certificate until you import the CA.\n'
fi

# Do not replace a manually maintained reverse-proxy configuration.
if [[ "$host_kind" != local && -e Caddyfile ]] &&
   ! grep -Fxq '# Generated by Uptime Platform install.sh' Caddyfile; then
  fail 'Existing Caddyfile is not installer-managed; refusing to overwrite it.'
fi

# Administrator details; recover from input mistakes without restarting.
while true; do
  read -r -p 'Administrator email: ' admin_email || fail 'Input canceled.'
  [[ -n "${admin_email//[[:space:]]/}" ]] && break
  printf 'Email cannot be empty. Try again.\n' >&2
done

while true; do
  read -r -p 'Organization name: ' organization || fail 'Input canceled.'
  if [[ -n "${organization//[[:space:]]/}" && ${#organization} -le 100 ]]; then
    break
  fi
  printf 'Organization name must contain 1-100 characters. Try again.\n' >&2
done

while true; do
  read -r -s -p 'Administrator password (12-128 characters): ' admin_password ||
    fail 'Input canceled.'
  printf '\n'

  if (( ${#admin_password} < 12 || ${#admin_password} > 128 )); then
    printf 'Password must contain 12-128 characters. Try again.\n\n' >&2
    unset admin_password
    continue
  fi

  read -r -s -p 'Confirm password: ' password_confirmation || fail 'Input canceled.'
  printf '\n'

  if [[ "$admin_password" != "$password_confirmation" ]]; then
    printf 'Passwords do not match. Try again.\n\n' >&2
    unset admin_password password_confirmation
    continue
  fi

  unset password_confirmation
  break
done

printf '\nAddress: %s\nAdministrator: %s\n' "$app_url" "$admin_email"
read -r -p 'Continue installation? [y/N]: ' confirmation || fail 'Input canceled.'
[[ "$confirmation" == [yY] ]] || fail 'Installation canceled.'

# Generate configuration only once; never rotate existing database/JWT secrets.
if [[ ! -f .env ]]; then
  tmp_env="$(mktemp .env.XXXXXXXX)"
  {
    printf '# Generated by Uptime Platform install.sh\n'
    printf 'UPTIME_HOST=%s\n' "$host"
    printf 'POSTGRES_DB=uptime\nPOSTGRES_USER=uptime\n'
    printf 'POSTGRES_PASSWORD=%s\n' "$(openssl rand -hex 24)"
    printf 'JWT_SECRET=%s\n' "$(openssl rand -hex 32)"
    printf 'API_KEY_HASH_SECRET=%s\n' "$(openssl rand -hex 32)"
    printf 'REFRESH_TOKEN_HASH_SECRET=%s\n' "$(openssl rand -hex 32)"

    if [[ "$host_kind" == local ]]; then
      printf 'REFRESH_COOKIE_SECURE=false\n'
    else
      printf 'REFRESH_COOKIE_SECURE=true\n'
    fi

    printf 'REFRESH_COOKIE_SAMESITE=lax\n'
    printf 'CORS_ALLOWED_ORIGINS=%s\n' "$app_url"
    printf 'APP_IMAGE=uptime-platform:installer\n'
  } > "$tmp_env"

  mv "$tmp_env" .env
fi

# Let the original sudo user run Compose; do not grant group/world read access.
if [[ -n "${SUDO_UID:-}" && "$SUDO_UID" != 0 ]]; then
  chown "$SUDO_UID:${SUDO_GID:-$SUDO_UID}" .env
fi
chmod 600 .env

# Only public installations need Caddy and its configuration.
if [[ "$host_kind" != local ]]; then
  tmp_caddy="$(mktemp Caddyfile.XXXXXXXX)"
  {
    printf '# Generated by Uptime Platform install.sh\n'
    if [[ "$host_kind" == ip ]]; then
      printf '{\n    default_sni %s\n}\n\n' "$host"
    fi
    printf '%s {\n' "$host"
    if [[ "$host_kind" == ip ]]; then
      printf '    tls internal\n'
    fi
    printf '    reverse_proxy frontend:80\n}\n'
  } > "$tmp_caddy"

  if [[ -f Caddyfile ]] && cmp -s "$tmp_caddy" Caddyfile; then
    rm -f "$tmp_caddy"
  else
    mv -f "$tmp_caddy" Caddyfile
  fi
  chmod 644 Caddyfile
fi

# Validate the selected mode before starting any service.
if [[ "$host_kind" == local ]]; then
  docker compose config --quiet || fail 'Invalid Compose configuration.'
else
  docker compose --profile public config --quiet || fail 'Invalid Compose configuration.'
  docker compose --profile public config --services | grep -Fxq caddy ||
    fail 'Caddy service is missing from compose.yml.'
fi

printf '\n[1/5] Building backend and frontend...\n'
docker build -t uptime-platform:installer .
docker compose build frontend

printf '[2/5] Starting PostgreSQL, migrations and API...\n'
docker compose up -d --wait api

printf '[3/5] Creating or verifying organization owner...\n'
printf '%s\n' "$admin_password" |
  docker compose run --rm -T --no-deps api \
    python -m uptime_platform.cli bootstrap-admin \
    --email "$admin_email" --organization "$organization"
unset admin_password

printf '[4/5] Starting remaining services...\n'
docker compose up -d --wait frontend scheduler notification-worker

if [[ "$host_kind" != local ]]; then
  printf 'Starting HTTPS reverse proxy...\n'
  # A bind-mounted Caddyfile may refer to the old inode after atomic replacement.
  docker compose --profile public up -d --force-recreate caddy
fi

printf '[5/5] Checking frontend and backend...\n'
curl_opts=(--noproxy '*' --fail --silent --show-error --max-time 6)

if [[ "$host_kind" == local ]]; then
  curl_opts+=(--resolve "$host:8080:127.0.0.1")
else
  curl_opts+=(--resolve "$host:443:127.0.0.1")
  if [[ "$host_kind" == ip ]]; then
    # Local smoke test only; does not establish public certificate trust.
    curl_opts+=(-k)
  fi
fi

check_api() {
  local response
  response="$(curl "${curl_opts[@]}" "$app_url/backend/health" 2>/dev/null)" || return 1
  python3 -c 'import json,sys; sys.exit(0 if json.loads(sys.argv[1]).get("status") == "ok" else 1)' \
    "$response" 2>/dev/null
}

ready=0
for attempt in {1..60}; do
  if curl "${curl_opts[@]}" "$app_url/" -o /dev/null 2>/dev/null && check_api; then
    ready=1
    break
  fi
  printf 'Waiting for frontend and API... %s/60\n' "$attempt"
  sleep 5
done

if [[ "$ready" != 1 ]]; then
  printf '\nFrontend diagnostics:\n' >&2
  curl "${curl_opts[@]}" "$app_url/" -o /dev/null \
    -w 'HTTP status: %{http_code}\n' || true
  printf '\nBackend diagnostics:\n' >&2
  curl "${curl_opts[@]}" "$app_url/backend/health" -o /dev/null \
    -w 'HTTP status: %{http_code}\n' || true
  if [[ "$host_kind" != local ]]; then
    printf '\nCaddy logs:\n' >&2
    docker compose --profile public logs --tail=50 caddy || true
  fi
  fail 'Installation checks failed. Configuration, database and volumes were preserved.'
fi

printf '\nInstallation completed.\nURL: %s\nAdministrator: %s\n' \
  "$app_url" "$admin_email"

if [[ "$host_kind" == ip ]]; then
  printf '\nIMPORTANT: HTTPS uses a private Caddy CA for this IP.\n'
  printf 'The browser will not trust it until the CA is installed on the client.\n'
fi