#!/usr/bin/env bash

set -Eeuo pipefail
umask 077

cd "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"

fail() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

# System checks

[[ $EUID -eq 0 ]] || fail \
  'Run with sudo: sudo bash install.sh'

[[ -t 0 ]] || fail \
  'Interactive terminal required.'

[[ -f compose.yml && -f Dockerfile && -f frontend/Dockerfile ]] || fail \
  'Run the installer from the project checkout.'

for command in docker curl openssl python3; do
  command -v "$command" >/dev/null 2>&1 || fail \
    "Missing dependency: $command"
done

docker info >/dev/null 2>&1 || fail \
  'Docker daemon is not running or is inaccessible.'

docker compose version >/dev/null 2>&1 || fail \
  'Docker Compose v2 is required.'


# Address validation

classify_host() {
  python3 - "$1" <<'PY'
import ipaddress
import re
import sys

host = sys.argv[1]

try:
    ipaddress.IPv4Address(host)
except ipaddress.AddressValueError:
    label = r"[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?"

    if len(host) > 253 or not re.fullmatch(
        rf"(?:{label}\.)+{label}",
        host.lower(),
    ):
        sys.exit(1)

    if re.fullmatch(r"[0-9.]+", host):
        sys.exit(1)

    print("domain")
else:
    print("ip")
PY
}


# Installation wizard

printf '\n=== Uptime Platform installer ===\n\n'

if [[ -f .env ]]; then
  grep -qx \
    '# Generated by Uptime Platform install.sh' \
    .env || fail \
    'Existing .env is not installer-managed. Back it up and configure manually.'

  host="$(sed -n 's/^UPTIME_HOST=//p' .env | head -n 1)"

  [[ -n "$host" ]] || fail \
    'Installed .env has no UPTIME_HOST.'

  printf 'Existing configuration detected. Keeping database and secrets.\n'
else
  read -r -p \
    'Domain (leave empty to detect public IPv4): ' \
    host

  if [[ -z "$host" ]]; then
    host="$(curl -4fsS --max-time 10 https://api.ipify.org)" || fail \
      'Cannot detect public IPv4. Enter it manually.'

    printf 'Detected address: %s\n' "$host"
  fi
fi

host_kind="$(classify_host "$host")" || fail \
  'Enter a valid IPv4 address or domain without https://, port, or path.'

if [[ "$host_kind" == 'domain' ]]; then
  getent ahostsv4 "$host" >/dev/null || fail \
    'Domain does not resolve to IPv4. Configure DNS first.'
else
  printf '\nWARNING: IP mode uses a private Caddy CA.\n'
  printf 'Browsers will NOT trust its certificate until the CA is installed.\n'
fi

if [[ -e Caddyfile ]] &&
   ! grep -qx \
     '# Generated by Uptime Platform install.sh' \
     Caddyfile; then

  fail \
    'Existing Caddyfile is not installer-managed; back it up before continuing.'
fi


# Administrator credentials

read -r -p 'Administrator email: ' admin_email
read -r -p 'Organization name: ' organization

[[ -n "${admin_email//[[:space:]]/}" &&
   -n "${organization//[[:space:]]/}" ]] || fail \
  'Email and organization are required.'

read -r -s -p \
  'Administrator password (12-128 characters): ' \
  admin_password

printf '\n'

read -r -s -p \
  'Confirm password: ' \
  password_confirmation

printf '\n'

[[ "$admin_password" == "$password_confirmation" ]] || fail \
  'Passwords do not match.'

[[ ${#admin_password} -ge 12 &&
   ${#admin_password} -le 128 ]] || fail \
  'Password length must be 12-128 characters.'

unset password_confirmation

printf '\nAddress: https://%s\nAdministrator: %s\n' \
  "$host" "$admin_email"

read -r -p 'Continue installation? [y/N]: ' confirmation

[[ "$confirmation" == [yY] ]] || fail \
  'Installation canceled.'


# Generate environment

if [[ ! -f .env ]]; then
  tmp_env="$(mktemp .env.XXXXXXXX)"

  {
    printf '# Generated by Uptime Platform install.sh\n'

    printf 'UPTIME_HOST=%s\n' "$host"

    printf 'POSTGRES_DB=uptime\n'
    printf 'POSTGRES_USER=uptime\n'

    printf 'POSTGRES_PASSWORD=%s\n' \
      "$(openssl rand -hex 24)"

    printf 'JWT_SECRET=%s\n' \
      "$(openssl rand -hex 32)"

    printf 'API_KEY_HASH_SECRET=%s\n' \
      "$(openssl rand -hex 32)"

    printf 'REFRESH_TOKEN_HASH_SECRET=%s\n' \
      "$(openssl rand -hex 32)"

    printf 'REFRESH_COOKIE_SECURE=true\n'
    printf 'REFRESH_COOKIE_SAMESITE=lax\n'

    printf 'CORS_ALLOWED_ORIGINS=https://%s\n' "$host"

    printf 'APP_IMAGE=uptime-platform:installer\n'

  } > "$tmp_env"

  mv "$tmp_env" .env
  chmod 600 .env
fi


# Generate Caddy configuration

if [[ ! -f Caddyfile ]]; then
  tmp_caddy="$(mktemp Caddyfile.XXXXXXXX)"

  {
    printf '# Generated by Uptime Platform install.sh\n'

    printf '%s {\n' "$host"

    if [[ "$host_kind" == 'ip' ]]; then
      printf '    tls internal\n'
    fi

    printf '    reverse_proxy frontend:80\n'
    printf '}\n'

  } > "$tmp_caddy"

  mv "$tmp_caddy" Caddyfile
  chmod 644 Caddyfile
fi


# Validate Docker Compose

docker compose --profile public config --quiet || fail \
  'Invalid compose configuration.'

docker compose --profile public config --services |
  grep -qx 'caddy' || fail \
  'Caddy service is missing from compose.yml.'


# Build application

printf '\n[1/5] Building backend and frontend...\n'

docker build -t uptime-platform:installer .

docker compose build frontend


# Initialize database and API

printf '[2/5] Starting database, applying migrations and starting API...\n'

docker compose up -d --wait api


# Bootstrap first administrator

printf '[3/5] Creating initial organization owner...\n'

printf '%s\n' "$admin_password" |
  docker compose run --rm -T --no-deps \
    api python -m uptime_platform.cli bootstrap-admin \
      --email "$admin_email" \
      --organization "$organization"

unset admin_password


# Start remaining services

printf '[4/5] Starting platform services and HTTPS...\n'

docker compose up -d --wait \
  frontend \
  scheduler \
  notification-worker

docker compose --profile public up -d caddy


# Installation checks

printf '[5/5] Checking HTTPS and backend...\n'

ready=0

for attempt in {1..30}; do
  curl_opts=(
    --noproxy '*'
    -fsS
    --max-time 5
    --resolve "$host:443:127.0.0.1"
  )

  if [[ "$host_kind" == 'ip' ]]; then
    # Only for local smoke checks.
    # The certificate is not publicly trusted.
    curl_opts+=(-k)
  fi

  if curl "${curl_opts[@]}" \
       "https://$host/" >/dev/null 2>&1 &&
     curl "${curl_opts[@]}" \
       "https://$host/backend/health" >/dev/null 2>&1; then

    ready=1
    break
  fi

  sleep 4
done

[[ $ready -eq 1 ]] || fail \
  'HTTPS smoke check failed. Inspect docker compose --profile public logs caddy frontend api. Services and database are preserved.'


# Final information

printf '\nInstallation completed.\n'
printf 'URL: https://%s\n' "$host"
printf 'Administrator: %s\n' "$admin_email"

if [[ "$host_kind" == 'ip' ]]; then
  printf '\nIP certificate is issued by a private CA.\n'
  printf 'Configure browser trust before entering credentials.\n'
fi