#!/usr/bin/env bash
set -Eeuo pipefail
umask 077

# Standalone installer: the Compose manifest is embedded below.
# Docker and Docker Compose v2 must already be installed.
INSTALL_DIR=/opt/uptime-platform
PROJECT_NAME=uptime-platform
MANAGED_MARKER='# Managed by Uptime Platform install.sh'

fail() {
  printf '\nERROR: %s\n' "$*" >&2
  exit 1
}

[[ $EUID -eq 0 ]] || fail 'Run with sudo: sudo bash install.sh'
[[ -t 0 ]] || fail 'An interactive terminal is required.'
for executable in docker curl openssl python3 getent mktemp cmp; do
  command -v "$executable" >/dev/null 2>&1 || fail "Missing dependency: $executable"
done
docker info >/dev/null 2>&1 || fail 'Docker daemon is unavailable.'
docker compose version >/dev/null 2>&1 || fail 'Docker Compose v2 is required.'
[[ ! -L "$INSTALL_DIR" ]] || fail "$INSTALL_DIR must not be a symlink."
[[ ! -e "$INSTALL_DIR" || -d "$INSTALL_DIR" ]] || fail "$INSTALL_DIR is not a directory."

# Never adopt somebody else's configuration or rotate an existing DB password.
for filename in .env compose.yml Caddyfile; do
  [[ ! -L "$INSTALL_DIR/$filename" ]] || fail "Refusing symlink $INSTALL_DIR/$filename"
done
if [[ -f "$INSTALL_DIR/.env" ]]; then
  grep -Fxq '# Generated by Uptime Platform install.sh' "$INSTALL_DIR/.env" ||
    fail 'An existing .env is not installer-managed; it will not be overwritten.'
  existing_install=1
else
  existing_install=0
  existing_containers="$(docker ps -aq --filter "label=com.docker.compose.project=$PROJECT_NAME")"
  [[ -z "$existing_containers" ]] || fail \
    "A $PROJECT_NAME Compose project already exists outside this installation. Stop and migrate it explicitly. No data were touched."
  if docker volume inspect "${PROJECT_NAME}_postgres_data" >/dev/null 2>&1; then
    fail 'An existing PostgreSQL volume was found without installer-managed .env. Refusing to generate new database credentials.'
  fi
fi

classify_host() {
  if [[ "$1" == localhost || "$1" == 127.0.0.1 ]]; then
    printf 'local\n'
    return 0
  fi
  python3 - "$1" <<'PY_HOST'
import ipaddress
import re
import sys

host = sys.argv[1]
try:
    ipaddress.IPv4Address(host)
except ipaddress.AddressValueError:
    label = r"[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?"
    if len(host) > 253 or not re.fullmatch(rf"(?:{label}\.)+{label}", host):
        sys.exit(1)
    if re.fullmatch(r"[0-9.]+", host):
        sys.exit(1)
    print("domain")
else:
    print("ip")
PY_HOST
}

printf '\n=== Uptime Platform installer ===\n'
printf 'Install location: %s\n\n' "$INSTALL_DIR"

if (( existing_install )); then
  host="$(sed -n 's/^UPTIME_HOST=//p' "$INSTALL_DIR/.env" | head -n 1)"
  [[ -n "$host" ]] || fail 'Existing .env does not define UPTIME_HOST.'
  printf 'Existing installation detected: keeping its address, secrets and PostgreSQL volume.\n'
  printf 'Enter the same administrator email and organization if bootstrap has already run.\n'
else
  while true; do
    read -r -p 'Address (localhost, domain, IPv4; blank = public IPv4): ' host || fail 'Input canceled.'
    if [[ -z "$host" ]]; then
      if ! host="$(curl --noproxy '*' -4fsS --max-time 10 https://api.ipify.org)"; then
        printf 'IP detection failed. Enter an address manually.\n' >&2
        continue
      fi
      printf 'Detected public outbound IP: %s\n' "$host"
      printf 'Note: NAT, CGNAT or firewall rules can still block incoming access.\n'
    fi
    host="${host,,}"
    if ! host_kind="$(classify_host "$host")"; then
      printf 'Invalid address. Use localhost, a domain or an IPv4 without a scheme, port or path.\n' >&2
      continue
    fi
    if [[ "$host_kind" == domain ]] && ! getent ahostsv4 "$host" >/dev/null; then
      printf 'Domain has no IPv4 DNS record. Check DNS and try again.\n' >&2
      continue
    fi
    break
  done
fi

host_kind="$(classify_host "$host")" || fail 'Invalid address in existing .env.'
if [[ "$host_kind" == local ]]; then
  app_url="http://${host}:8080"
  printf '\nLocal mode: only this computer can access %s\n' "$app_url"
else
  app_url="https://${host}"
  if [[ "$host_kind" == domain ]]; then
    getent ahostsv4 "$host" >/dev/null || fail 'Domain does not resolve to IPv4.'
    printf '\nDomain mode: ports 80 and 443 must be publicly reachable.\n'
  else
    printf '\nWARNING: IP mode uses a private Caddy CA. Remote browsers will NOT trust its certificate.\n'
    printf 'Import the CA certificate on client devices before entering credentials.\n'
  fi
fi

if [[ -f "$INSTALL_DIR/compose.yml" ]] &&
   ! grep -Fxq "$MANAGED_MARKER" "$INSTALL_DIR/compose.yml"; then
  fail 'Existing compose.yml is not installer-managed; refusing to overwrite it.'
fi
if [[ "$host_kind" != local && -e "$INSTALL_DIR/Caddyfile" ]] &&
   ! grep -Fxq '# Generated by Uptime Platform install.sh' "$INSTALL_DIR/Caddyfile"; then
  fail 'Existing Caddyfile is not installer-managed; refusing to overwrite it.'
fi

# Port checks are only for brand-new installs; re-runs use their own containers.
if (( ! existing_install )); then
  python3 - "$host_kind" <<'PY_PORTS' || fail 'Required TCP ports are already occupied.'
import socket
import sys

ports = [("127.0.0.1", 8080)]
if sys.argv[1] != "local":
    ports.extend([("0.0.0.0", 80), ("0.0.0.0", 443)])
for address, port in ports:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        try:
            sock.bind((address, port))
        except OSError as error:
            print(f"Port {address}:{port} unavailable: {error}", file=sys.stderr)
            sys.exit(1)
PY_PORTS
fi

while true; do
  read -r -p 'Administrator email: ' admin_email || fail 'Input canceled.'
  [[ -n "${admin_email//[[:space:]]/}" ]] && break
  printf 'Email cannot be empty.\n' >&2
done
while true; do
  read -r -p 'Organization name: ' organization || fail 'Input canceled.'
  if [[ -n "${organization//[[:space:]]/}" && ${#organization} -le 100 ]]; then
    break
  fi
  printf 'Organization name must contain 1-100 characters.\n' >&2
done
while true; do
  read -r -s -p 'Administrator password (12-128 characters): ' admin_password || fail 'Input canceled.'
  printf '\n'
  if (( ${#admin_password} < 12 || ${#admin_password} > 128 )); then
    printf 'Password must contain 12-128 characters. Try again.\n\n' >&2
    unset admin_password
    continue
  fi
  read -r -s -p 'Confirm password: ' password_confirmation || fail 'Input canceled.'
  printf '\n'
  if [[ "$admin_password" != "$password_confirmation" ]]; then
    printf 'Passwords do not match. Try again.\n\n' >&2
    unset admin_password password_confirmation
    continue
  fi
  unset password_confirmation
  break
done

printf '\nURL: %s\nAdministrator: %s\n' "$app_url" "$admin_email"
if (( existing_install )); then
  printf 'The existing admin password will NOT be changed. The latest images will be pulled.\n'
fi
read -r -p 'Continue? [y/N]: ' confirmation || fail 'Input canceled.'
[[ "$confirmation" == [yY] ]] || fail 'Installation canceled.'

mkdir -p -- "$INSTALL_DIR"
chmod 755 "$INSTALL_DIR"

# Write the complete image-only Compose manifest from this one install.sh.
tmp_compose="$(mktemp "$INSTALL_DIR/compose.yml.XXXXXXXX")"
cat > "$tmp_compose" <<'COMPOSE_YAML'
# Managed by Uptime Platform install.sh
# Application images use :latest; this file never builds sources.
name: uptime-platform

services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-uptime}
      POSTGRES_USER: ${POSTGRES_USER:-uptime}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U "$${POSTGRES_USER}" -d "$${POSTGRES_DB}"
      interval: 5s
      timeout: 5s
      retries: 10

  migrate:
    image: ${APP_IMAGE:-sashastudent/uptime-platform:latest}
    restart: "no"
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-uptime}:${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}@postgres:5432/${POSTGRES_DB:-uptime}
      NOTIFICATION_TIMEOUT_SECONDS: ${NOTIFICATION_TIMEOUT_SECONDS:-5}
    command: ["alembic", "upgrade", "head"]
    depends_on:
      postgres:
        condition: service_healthy

  api:
    image: ${APP_IMAGE:-sashastudent/uptime-platform:latest}
    restart: unless-stopped
    cap_add:
      - NET_RAW
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-uptime}:${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}@postgres:5432/${POSTGRES_DB:-uptime}
      NOTIFICATION_TIMEOUT_SECONDS: ${NOTIFICATION_TIMEOUT_SECONDS:-5}
      JWT_SECRET: ${JWT_SECRET:?JWT_SECRET is required}
      JWT_ACCESS_TOKEN_TTL_MINUTES: ${JWT_ACCESS_TOKEN_TTL_MINUTES:-60}
      API_KEY_HASH_SECRET: ${API_KEY_HASH_SECRET:?API_KEY_HASH_SECRET is required}
      REFRESH_TOKEN_HASH_SECRET: ${REFRESH_TOKEN_HASH_SECRET:?REFRESH_TOKEN_HASH_SECRET is required}
      REFRESH_TOKEN_TTL_DAYS: ${REFRESH_TOKEN_TTL_DAYS:-30}
      REFRESH_COOKIE_NAME: ${REFRESH_COOKIE_NAME:-refresh_token}
      REFRESH_COOKIE_SECURE: ${REFRESH_COOKIE_SECURE:-false}
      REFRESH_COOKIE_SAMESITE: ${REFRESH_COOKIE_SAMESITE:-lax}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS:-http://localhost:8080}
    command:
      - fastapi
      - run
      - src/uptime_platform/main.py
      - --host
      - 0.0.0.0
      - --port
      - "8000"
    depends_on:
      migrate:
        condition: service_completed_successfully
    healthcheck:
      test:
        - CMD
        - python
        - -c
        - "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/health', timeout=2)"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  frontend:
    image: ${FRONTEND_IMAGE:-sashastudent/uptime-platform-frontend:latest}
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      api:
        condition: service_healthy

  scheduler:
    image: ${APP_IMAGE:-sashastudent/uptime-platform:latest}
    restart: unless-stopped
    cap_add:
      - NET_RAW
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-uptime}:${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}@postgres:5432/${POSTGRES_DB:-uptime}
      NOTIFICATION_TIMEOUT_SECONDS: ${NOTIFICATION_TIMEOUT_SECONDS:-5}
    command: ["python", "-m", "uptime_platform.scheduler.main"]
    depends_on:
      migrate:
        condition: service_completed_successfully

  notification-worker:
    image: ${APP_IMAGE:-sashastudent/uptime-platform:latest}
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER:-uptime}:${POSTGRES_PASSWORD:?POSTGRES_PASSWORD is required}@postgres:5432/${POSTGRES_DB:-uptime}
      NOTIFICATION_TIMEOUT_SECONDS: ${NOTIFICATION_TIMEOUT_SECONDS:-5}
    command: ["python", "-m", "uptime_platform.notifications.main"]
    depends_on:
      migrate:
        condition: service_completed_successfully

  postgres-test:
    image: postgres:17-alpine
    profiles: ["test"]
    environment:
      POSTGRES_DB: uptime_test
      POSTGRES_USER: uptime
      POSTGRES_PASSWORD: uptime
    ports:
      - "127.0.0.1:5433:5432"
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U uptime -d uptime_test"]
      interval: 2s
      timeout: 5s
      retries: 10

  mailpit:
    image: axllent/mailpit:latest
    profiles: ["mail"]
    ports:
      - "127.0.0.1:1025:1025"
      - "127.0.0.1:8025:8025"

  caddy:
    image: caddy:2
    profiles: ["public"]
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      frontend:
        condition: service_started

volumes:
  postgres_data:
  caddy_data:
  caddy_config:
COMPOSE_YAML
if [[ -f "$INSTALL_DIR/compose.yml" ]] && cmp -s "$tmp_compose" "$INSTALL_DIR/compose.yml"; then
  rm -f "$tmp_compose"
else
  mv -f "$tmp_compose" "$INSTALL_DIR/compose.yml"
fi
chmod 644 "$INSTALL_DIR/compose.yml"

# Secrets are created once; losing .env while keeping the volume is not recoverable
# by simply generating a new password.
if (( ! existing_install )); then
  tmp_env="$(mktemp "$INSTALL_DIR/.env.XXXXXXXX")"
  {
    printf '# Generated by Uptime Platform install.sh\n'
    printf 'UPTIME_HOST=%s\n' "$host"
    printf 'POSTGRES_DB=uptime\nPOSTGRES_USER=uptime\n'
    printf 'POSTGRES_PASSWORD=%s\n' "$(openssl rand -hex 24)"
    printf 'JWT_SECRET=%s\n' "$(openssl rand -hex 32)"
    printf 'API_KEY_HASH_SECRET=%s\n' "$(openssl rand -hex 32)"
    printf 'REFRESH_TOKEN_HASH_SECRET=%s\n' "$(openssl rand -hex 32)"
    if [[ "$host_kind" == local ]]; then
      printf 'REFRESH_COOKIE_SECURE=false\n'
    else
      printf 'REFRESH_COOKIE_SECURE=true\n'
    fi
    printf 'REFRESH_COOKIE_SAMESITE=lax\n'
    printf 'CORS_ALLOWED_ORIGINS=%s\n' "$app_url"
    printf 'APP_IMAGE=sashastudent/uptime-platform:latest\n'
    printf 'FRONTEND_IMAGE=sashastudent/uptime-platform-frontend:latest\n'
  } > "$tmp_env"
  mv -f "$tmp_env" "$INSTALL_DIR/.env"
fi
if [[ -n "${SUDO_UID:-}" && "$SUDO_UID" != 0 ]]; then
  chown "$SUDO_UID:${SUDO_GID:-$SUDO_UID}" "$INSTALL_DIR/.env"
fi
chmod 600 "$INSTALL_DIR/.env"

if [[ "$host_kind" != local ]]; then
  tmp_caddy="$(mktemp "$INSTALL_DIR/Caddyfile.XXXXXXXX")"
  {
    printf '# Generated by Uptime Platform install.sh\n'
    if [[ "$host_kind" == ip ]]; then
      printf '{\n    default_sni %s\n}\n\n' "$host"
    fi
    printf '%s {\n' "$host"
    if [[ "$host_kind" == ip ]]; then
      printf '    tls internal\n'
    fi
    printf '    reverse_proxy frontend:80\n}\n'
  } > "$tmp_caddy"
  if [[ -f "$INSTALL_DIR/Caddyfile" ]] && cmp -s "$tmp_caddy" "$INSTALL_DIR/Caddyfile"; then
    rm -f "$tmp_caddy"
  else
    mv -f "$tmp_caddy" "$INSTALL_DIR/Caddyfile"
  fi
  chmod 644 "$INSTALL_DIR/Caddyfile"
fi

cd "$INSTALL_DIR"

if [[ "$host_kind" == local ]]; then
  docker compose config --quiet || fail 'Invalid Compose configuration.'
else
  docker compose --profile public config --quiet || fail 'Invalid Compose configuration.'
fi

printf '\n[1/5] Pulling latest application and dependency images...\n'
if [[ "$host_kind" == local ]]; then
  docker compose pull --policy always
else
  docker compose --profile public pull --policy always
fi

# Detect an outdated/incorrectly published :latest image before touching the database.
docker compose run --rm -T --no-deps api \
  python -m uptime_platform.cli --help >/dev/null || \
  fail 'Backend :latest image is missing the bootstrap CLI. Publish the correct image first.'

printf '[2/5] Starting PostgreSQL, migrations and API...\n'
docker compose up -d --no-build --wait api

printf '[3/5] Creating/verifying the initial organization owner...\n'
printf '%s\n' "$admin_password" |
  docker compose run --rm -T --no-deps api \
    python -m uptime_platform.cli bootstrap-admin \
    --email "$admin_email" --organization "$organization"
unset admin_password

printf '[4/5] Starting frontend, scheduler and notification worker...\n'
docker compose up -d --no-build --wait frontend scheduler notification-worker
if [[ "$host_kind" != local ]]; then
  docker compose --profile public up -d --no-build --force-recreate caddy
fi

printf '[5/5] Checking frontend and API...\n'
curl_opts=(--noproxy '*' --fail --silent --show-error --max-time 6)
if [[ "$host_kind" == local ]]; then
  curl_opts+=(--resolve "$host:8080:127.0.0.1")
else
  curl_opts+=(--resolve "$host:443:127.0.0.1")
  if [[ "$host_kind" == ip ]]; then
    # Local smoke test only; this does not make the CA trusted in a browser.
    curl_opts+=(-k)
  fi
fi

check_api() {
  local response
  response="$(curl "${curl_opts[@]}" "$app_url/backend/health" 2>/dev/null)" || return 1
  python3 -c \
    'import json,sys; sys.exit(0 if json.loads(sys.argv[1]).get("status") == "ok" else 1)' \
    "$response" 2>/dev/null
}

ready=0
for attempt in {1..60}; do
  if curl "${curl_opts[@]}" "$app_url/" -o /dev/null 2>/dev/null && check_api; then
    ready=1
    break
  fi
  printf 'Waiting for frontend and API... %s/60\n' "$attempt"
  sleep 5
done

if (( ! ready )); then
  printf '\nFrontend diagnostics:\n' >&2
  curl "${curl_opts[@]}" "$app_url/" -o /dev/null \
    -w 'HTTP status: %{http_code}\n' || true
  printf '\nAPI diagnostics:\n' >&2
  curl "${curl_opts[@]}" "$app_url/backend/health" -o /dev/null \
    -w 'HTTP status: %{http_code}\n' || true
  if [[ "$host_kind" != local ]]; then
    printf '\nCaddy logs:\n' >&2
    docker compose --profile public logs --tail=50 caddy || true
  fi
  fail "Installation checks failed. Data preserved in $INSTALL_DIR and Docker volumes."
fi

printf '\nInstallation completed.\nURL: %s\nAdministrator: %s\n' \
  "$app_url" "$admin_email"
printf 'Installation directory: %s\n' "$INSTALL_DIR"
if [[ "$host_kind" == ip ]]; then
  printf '\nWARNING: Browser trust of the Caddy private CA must be configured separately.\n'
fi
