#!/usr/bin/env bash
set -Eeuo pipefail
umask 077

unset COMPOSE_FILE COMPOSE_PROJECT_NAME COMPOSE_PROFILES COMPOSE_ENV_FILES COMPOSE_PATH_SEPARATOR
unset APP_IMAGE FRONTEND_IMAGE FRONTEND_PORT POSTGRES_DB POSTGRES_USER POSTGRES_PASSWORD
unset JWT_SECRET JWT_ACCESS_TOKEN_TTL_MINUTES API_KEY_HASH_SECRET REFRESH_TOKEN_HASH_SECRET
unset REFRESH_TOKEN_TTL_DAYS REFRESH_COOKIE_NAME REFRESH_COOKIE_SECURE REFRESH_COOKIE_SAMESITE
unset CORS_ALLOWED_ORIGINS NOTIFICATION_TIMEOUT_SECONDS UPTIME_HOST
unset RETENTION_ENABLED RETENTION_CHECKS_DAYS RETENTION_INCIDENTS_DAYS
unset RETENTION_NOTIFICATIONS_DAYS RETENTION_INTERVAL_SECONDS RETENTION_BATCH_SIZE

RELEASE_VERSION=1.2.1
UPDATER_REVISION=5
RELEASE_BASE=https://raw.githubusercontent.com/nightingale-develop/uptime-platform
INSTALL_DIR=/opt/uptime-platform
LOCK_FILE=/run/lock/uptime-platform.lock
VERSION=$RELEASE_VERSION
OBSERVABILITY=0
MANAGED_MARKER='# Managed by Uptime Platform install.sh'
stage=
backup=
stopped=0

fail() {
  printf '\nERROR: %s\n' "$*" >&2
  exit 1
}

while (($#)); do
  case "$1" in
    --version)
      (($# >= 2)) || fail '--version needs a release number.'
      VERSION=$2
      shift 2
      ;;
    --observability)
      OBSERVABILITY=1
      shift
      ;;
    --help)
      printf 'Usage: sudo bash update.sh [--version X.Y.Z] [--observability]\n'
      exit 0
      ;;
    *) fail "Unknown argument: $1" ;;
  esac
done

[[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || fail 'Use a release number such as 1.2.1, not latest.'
for executable in docker curl flock mktemp awk cp find grep; do
  command -v "$executable" >/dev/null 2>&1 || fail "Missing dependency: $executable"
done
[[ -d "$INSTALL_DIR" && ! -L "$INSTALL_DIR" ]] || fail 'Installation directory is missing or is a symlink.'
[[ -w "$INSTALL_DIR" ]] || fail 'Installation directory is not writable. Run with sudo.'
INSTALL_DIR=$(cd -- "$INSTALL_DIR" && pwd -P)
for filename in .env compose.yml Caddyfile update.sh observability backups; do
  [[ ! -L "$INSTALL_DIR/$filename" ]] || fail "Refusing symlink: $filename"
done
[[ -f "$INSTALL_DIR/.env" && -f "$INSTALL_DIR/compose.yml" ]] || fail 'Existing .env and compose.yml are required. Use install.sh for a new installation.'
grep -Fxq '# Generated by Uptime Platform install.sh' "$INSTALL_DIR/.env" || fail '.env is not installer-managed.'
grep -Fxq "$MANAGED_MARKER" "$INSTALL_DIR/compose.yml" || fail 'Compose is not installer-managed. Use install.sh --clean for a fresh installation.'
[[ ! -d "$INSTALL_DIR/observability" ]] || [[ -z "$(find "$INSTALL_DIR/observability" -type l -print -quit)" ]] || fail 'Refusing symlinks inside observability configuration.'
[[ ! -L "$LOCK_FILE" ]] || fail 'Refusing a symlink at the installation lock.'
exec 9>"$LOCK_FILE"
flock -n 9 || fail 'Another installation or update is running.'
docker info >/dev/null 2>&1 || fail 'Docker daemon is unavailable.'
docker compose version >/dev/null 2>&1 || fail 'Docker Compose v2 is required.'

cleanup() {
  local status=$?
  trap - EXIT
  if [[ -n "$stage" ]]; then
    rm -rf -- "$stage"
  fi
  if ((status != 0)); then
    [[ -z "$backup" ]] || printf 'Backup retained at %s\n' "$backup" >&2
    if ((stopped)); then
      printf 'Application processes were stopped. Inspect the error before restarting. No volumes were deleted; no automatic database rollback was attempted.\n' >&2
    fi
  fi
  exit "$status"
}
trap cleanup EXIT

current() {
  docker compose --project-name uptime-platform --project-directory "$INSTALL_DIR" \
    --env-file "$INSTALL_DIR/.env" -f "$INSTALL_DIR/compose.yml" "$@"
}

project_containers=$(docker ps -aq --filter label=com.docker.compose.project=uptime-platform --filter label=com.docker.compose.oneoff=False)
for container in $project_containers; do
  service=$(docker inspect --format '{{index .Config.Labels "com.docker.compose.service"}}' "$container")
  case "$service" in
    api|frontend|scheduler|notification-worker|postgres|prometheus|grafana|caddy)
      directory=$(docker inspect --format '{{index .Config.Labels "com.docker.compose.project.working_dir"}}' "$container")
      [[ "$directory" == "$INSTALL_DIR" ]] || fail "Service $service belongs to $directory. This updater only manages $INSTALL_DIR. Run install.sh --clean to replace the old deployment."
      ;;
  esac
done

profiles=()
[[ ! -f "$INSTALL_DIR/Caddyfile" ]] || profiles+=(--profile public)
existing_services=$(current ps -a --services)
if [[ "$existing_services" == *prometheus* || "$existing_services" == *grafana* ]]; then
  OBSERVABILITY=1
fi
((OBSERVABILITY == 0)) || profiles+=(--profile observability)

stage=$(mktemp -d "$INSTALL_DIR/.update.XXXXXXXX")
printf 'Downloading deployment files for %s...\n' "$VERSION"
files=(
  compose.yml update.sh
  observability/prometheus/prometheus.yml
  observability/prometheus/alerts.yml
  observability/prometheus/alerts.test.yml
  observability/grafana/provisioning/datasources/prometheus.yml
  observability/grafana/provisioning/dashboards/uptime.yml
  observability/grafana/dashboards/uptime-platform.json
)
for file in "${files[@]}"; do
  mkdir -p -- "$stage/$(dirname "$file")"
  curl --fail --silent --show-error --location --proto '=https' --tlsv1.2 \
    --connect-timeout 15 --max-time 120 \
    "$RELEASE_BASE/v$VERSION/$file" -o "$stage/$file"
done
bash -n "$stage/update.sh"
downloaded_revision=$(awk -F= '/^UPDATER_REVISION=/ { print $2; exit }' "$stage/update.sh")
downloaded_revision=${downloaded_revision:-1}
[[ "$downloaded_revision" =~ ^[1-9][0-9]{0,8}$ ]] || fail 'Downloaded updater has an invalid revision.'
if ((downloaded_revision < UPDATER_REVISION)); then
  cp -- "${BASH_SOURCE[0]}" "$stage/update.sh"
fi
{ printf '%s\n' "$MANAGED_MARKER"; cat "$stage/compose.yml"; } > "$stage/compose.managed.yml"
mv "$stage/compose.managed.yml" "$stage/compose.yml"
cp -p "$INSTALL_DIR/.env" "$stage/.env"
awk -v version="$VERSION" '
  !/^[[:space:]]*(export[[:space:]]+)?(APP_IMAGE|FRONTEND_IMAGE)[[:space:]]*=/ { print }
  END {
    print "APP_IMAGE=sashastudent/uptime-platform:" version
    print "FRONTEND_IMAGE=sashastudent/uptime-platform-frontend:" version
  }
' "$INSTALL_DIR/.env" > "$stage/env.new"
cat "$stage/env.new" > "$stage/.env"
chmod 600 "$stage/.env"

staged() {
  APP_IMAGE="sashastudent/uptime-platform:$VERSION" \
  FRONTEND_IMAGE="sashastudent/uptime-platform-frontend:$VERSION" \
    docker compose --project-name uptime-platform --project-directory "$INSTALL_DIR" \
      --env-file "$stage/.env" -f "$stage/compose.yml" "${profiles[@]}" "$@"
}
staged config --quiet
printf 'Pulling application images before stopping any process...\n'
staged pull migrate api frontend scheduler notification-worker
if ((OBSERVABILITY)); then
  staged pull prometheus grafana
fi

printf 'Checking database access with the release migration image...\n'
staged run --rm --no-deps -T migrate alembic current >/dev/null 2>&1 ||
  fail 'Database preflight failed. No application processes were stopped or installation files replaced. Check that PostgreSQL is running and the installation credentials match the existing database. Changing POSTGRES_PASSWORD does not change the password stored in its volume.'

mkdir -p -- "$INSTALL_DIR/backups"
backup=$(mktemp -d "$INSTALL_DIR/backups/pre-$VERSION-$(date -u +%Y%m%dT%H%M%SZ).XXXXXXXX")
cp -p "$INSTALL_DIR/.env" "$INSTALL_DIR/compose.yml" "$backup/"
for file in Caddyfile update.sh observability; do
  [[ ! -e "$INSTALL_DIR/$file" ]] || cp -a "$INSTALL_DIR/$file" "$backup/"
done
printf 'Stopping application processes; backup directory: %s\n' "$backup"
stopped=1
current stop frontend api scheduler notification-worker
current exec -T postgres sh -c 'pg_dump -U "$POSTGRES_USER" "$POSTGRES_DB"' > "$backup/database.sql"
[[ -s "$backup/database.sql" ]] || fail 'Database backup is empty.'

find "$stage/observability" -type d -exec chmod 755 {} +
find "$stage/observability" -type f -exec chmod 644 {} +
if [[ -d "$INSTALL_DIR/observability" ]]; then
  mv "$INSTALL_DIR/observability" "$stage/previous-observability"
fi
mv "$stage/observability" "$INSTALL_DIR/observability"
chmod 644 "$stage/compose.yml"
chmod 755 "$stage/update.sh"
mv "$stage/compose.yml" "$INSTALL_DIR/compose.yml"
mv "$stage/update.sh" "$INSTALL_DIR/update.sh"
mv "$stage/.env" "$INSTALL_DIR/.env"

export APP_IMAGE="sashastudent/uptime-platform:$VERSION"
export FRONTEND_IMAGE="sashastudent/uptime-platform-frontend:$VERSION"
printf 'Applying migrations with release %s...\n' "$VERSION"
current "${profiles[@]}" run --rm --no-deps migrate
current "${profiles[@]}" up -d --no-deps --wait api scheduler notification-worker
current "${profiles[@]}" up -d --no-deps --wait frontend
if [[ -f "$INSTALL_DIR/Caddyfile" ]]; then
  current --profile public up -d --no-deps --wait caddy
fi
if ((OBSERVABILITY)); then
  current --profile observability up -d --no-deps --force-recreate --wait prometheus grafana
fi
current "${profiles[@]}" ps -a
stopped=0
printf '\nUpdated to %s. Backup: %s\n' "$VERSION" "$backup"
printf 'For the next release: sudo bash /opt/uptime-platform/update.sh --version X.Y.Z\n'
