{{- if .Values.notificationWorker.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "uptime-platform.fullname" . }}-notification-worker
  labels:
    {{- include "uptime-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: notification-worker
spec:
  replicas: {{ .Values.notificationWorker.replicas }}
  selector:
    matchLabels:
      {{- include "uptime-platform.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: notification-worker
  template:
    metadata:
      labels:
        {{- include "uptime-platform.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: notification-worker
    spec:
      {{- include "uptime-platform.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.migrations.enabled }}
      initContainers:
        {{- include "uptime-platform.migrationWaitInitContainer" . | nindent 8 }}
      {{- end }}
      containers:
        - name: notification-worker
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          securityContext:
            {{- include "uptime-platform.containerSecurityContext" . | nindent 12 }}
          command: ["python", "-m", "uptime_platform.notifications.main"]
          envFrom:
            - configMapRef:
                name: {{ include "uptime-platform.configMapName" . }}
            - secretRef:
                name: {{ include "uptime-platform.secretName" . }}
          ports:
            - name: metrics
              containerPort: 9002
              protocol: TCP
          resources:
            {{- toYaml .Values.notificationWorker.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
