import fcntl
import os
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]


@pytest.fixture
def deployment(tmp_path):
    install = tmp_path / "installation with spaces"
    install.mkdir()
    (install / ".env").write_text(
        "# Generated by Uptime Platform install.sh\n"
        "POSTGRES_PASSWORD='keep-this-$value'\n"
        "JWT_SECRET=keep-jwt\n"
        "APP_IMAGE=old-backend\nFRONTEND_IMAGE=old-frontend\n"
    )
    (install / "compose.yml").write_text(
        "# Managed by Uptime Platform install.sh\nname: uptime-platform\n"
    )
    executables = tmp_path / "bin"
    executables.mkdir()
    log = tmp_path / "commands"
    log.touch()
    scripts = {
        "curl": """#!/usr/bin/env bash
set -eu
printf 'download\\n' >> "$COMMAND_LOG"
[[ "${FAIL_AT:-}" != download ]] || exit 22
while (($#)); do
  case "$1" in
    https://*) source=${1#*/v1.2.0/}; shift ;;
    -o) target=$2; shift 2 ;;
    *) shift ;;
  esac
done
cp "$REPO_ROOT/$source" "$target"
""",
        "docker": """#!/usr/bin/env bash
set -eu
printf '%s\\n' "$*" >> "$COMMAND_LOG"
case " $* " in
  *' ps -a --services '*) printf '%s\\n' "${EXISTING_SERVICES:-api}" ;;
  *' config --quiet '*) [[ "${FAIL_AT:-}" != config ]] || exit 1 ;;
  *' pull '*) [[ "${FAIL_AT:-}" != pull ]] || exit 1 ;;
  *' exec -T postgres '* )
    [[ "${FAIL_AT:-}" != dump ]] || exit 1
    [[ "${FAIL_AT:-}" == empty_dump ]] || printf 'CREATE TABLE backup_proof (id int);\\n'
    ;;
  *' run --rm --no-deps migrate '*) [[ "${FAIL_AT:-}" != migrate ]] || exit 1 ;;
esac
exit 0
""",
    }
    for name, script in scripts.items():
        executable = executables / name
        executable.write_text(script)
        executable.chmod(0o755)
    env = {
        **os.environ,
        "PATH": f"{executables}:{os.environ['PATH']}",
        "COMMAND_LOG": str(log),
        "REPO_ROOT": str(ROOT),
    }
    return install, log, env


def run_update(deployment, *args):
    install, _, env = deployment
    return subprocess.run(
        ["bash", str(ROOT / "update.sh"), "--install-dir", str(install), *args],
        env=env,
        capture_output=True,
        text=True,
        check=False,
        timeout=15,
    )


@pytest.mark.parametrize("monitoring", [False, True])
def test_update_preserves_secrets_and_backs_up_before_migration(deployment, monitoring):
    install, log, env = deployment
    old_env = (install / ".env").read_text()
    (install / "Caddyfile").write_text("example.test { reverse_proxy frontend:80 }\n")
    if monitoring:
        env["EXISTING_SERVICES"] = "api\nprometheus\ngrafana"
    result = run_update(deployment)
    assert result.returncode == 0, result.stderr
    new_env = (install / ".env").read_text()
    assert "POSTGRES_PASSWORD='keep-this-$value'" in new_env
    assert "JWT_SECRET=keep-jwt" in new_env
    assert "APP_IMAGE=sashastudent/uptime-platform:1.2.0" in new_env
    assert "FRONTEND_IMAGE=sashastudent/uptime-platform-frontend:1.2.0" in new_env
    assert (install / ".env").stat().st_mode & 0o777 == 0o600
    backup = next((install / "backups").iterdir())
    assert (backup / ".env").read_text() == old_env
    assert "CREATE TABLE" in (backup / "database.sql").read_text()
    assert (backup / "database.sql").stat().st_mode & 0o777 == 0o600
    assert (install / "update.sh").read_text() == (ROOT / "update.sh").read_text()
    assert (install / "observability/prometheus/alerts.yml").is_file()
    assert all(path.name == ".update.lock" for path in install.glob(".update.*"))
    commands = log.read_text()
    assert commands.index(" pull ") < commands.index(" stop ")
    assert commands.index(" stop ") < commands.index("pg_dump")
    assert commands.index("pg_dump") < commands.index(" run --rm --no-deps migrate")
    assert commands.index(" run --rm --no-deps migrate") < commands.index(
        " up -d --no-deps --wait api"
    )
    assert "--profile public up -d --no-deps --wait caddy" in commands
    assert ("--force-recreate --wait prometheus grafana" in commands) is monitoring
    assert "keep-this" not in result.stdout + result.stderr + commands


@pytest.mark.parametrize(
    "failure", ["download", "config", "pull", "dump", "empty_dump"]
)
def test_failed_preparation_preserves_installed_files(deployment, failure):
    install, log, env = deployment
    old_env = (install / ".env").read_bytes()
    old_compose = (install / "compose.yml").read_bytes()
    env["FAIL_AT"] = failure
    result = run_update(deployment)
    assert result.returncode != 0
    assert (install / ".env").read_bytes() == old_env
    assert (install / "compose.yml").read_bytes() == old_compose
    commands = log.read_text()
    assert " run --rm --no-deps migrate" not in commands
    if failure in {"download", "config", "pull"}:
        assert " stop " not in commands


def test_failed_migration_does_not_start_writers(deployment):
    install, log, env = deployment
    env["FAIL_AT"] = "migrate"
    result = run_update(deployment)
    assert result.returncode != 0
    assert "Application processes were stopped" in result.stderr
    assert " up -d --no-deps --wait api" not in log.read_text()
    assert next((install / "backups").glob("*/database.sql")).is_file()


@pytest.mark.parametrize("unsafe", ["custom", "symlink", "locked", "latest"])
def test_refuses_unsafe_updates(deployment, unsafe):
    install, log, _ = deployment
    if unsafe == "custom":
        (install / "compose.yml").write_text("services: {}\n")
    elif unsafe == "symlink":
        (install / "backups").symlink_to(install.parent, target_is_directory=True)
    with (install / ".update.lock").open("w") as lock:
        if unsafe == "locked":
            fcntl.flock(lock, fcntl.LOCK_EX | fcntl.LOCK_NB)
        args = ["--version", "latest"] if unsafe == "latest" else []
        result = run_update(deployment, *args)
    assert result.returncode != 0
    assert " stop " not in log.read_text()
    assert "download" not in log.read_text()


def test_can_enable_observability_during_update(deployment):
    result = run_update(deployment, "--observability")
    assert result.returncode == 0, result.stderr
    commands = deployment[1].read_text()
    assert "--profile observability pull prometheus grafana" in commands
    assert "--force-recreate --wait prometheus grafana" in commands
